#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Sep 24 20:18:55 IST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 99a71f8d496c4524bcc32b9bbb77c8ba --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot LEDblin_behav xil_defaultlib.LEDblin xil_defaultlib.glbl -log elaborate.log"
xelab -wto 99a71f8d496c4524bcc32b9bbb77c8ba --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot LEDblin_behav xil_defaultlib.LEDblin xil_defaultlib.glbl -log elaborate.log

